notifications:
  email: false

sudo: false

addons:
  postgresql: 9.4

services:
  - postgresql
  - redis
  - rabbitmq

language: python

cache:
  - pip

env:
  global:
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.1.tar.gz"
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.0-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    # ES6 + PostgreSQL
    - REQUIREMENTS=release EXTRAS=deploy,tests SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES6_DOWNLOAD_URL
    # ES7 + PostgreSQL
    - REQUIREMENTS=release EXTRAS=deploy-es7,tests SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES7_DOWNLOAD_URL DEPLOY=true

python:
  - "3.7"
  - "3.8"

matrix:
  fast_finish: true
#  allow_failures:
#    - env: REQUIREMENTS=release EXTRAS=all,postgresql,elasticsearch6 SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" ES_URL=$ES6_DOWNLOAD_URL

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - ${ES_URL} | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"
  - "travis_retry pip install --upgrade pip setuptools py pip-tools"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.in"
  - "cat .travis-release-requirements.in 2>&1"
  - "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
  - "cat .travis-release-requirements.txt 2>&1"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - /tmp/elasticsearch/bin/elasticsearch --version
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200 || cat /tmp/local-es.log
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "changeme"
  on:
    tags: true
  all_branches: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
